language: python
python:
  - 3.3
  - 3.4
  - 3.5

cache:
  pip: true
  directories:
    - env

env:
  global:
    - RANDOM_SEED=0

install:
  - make install

script:
  - make check
  - make test

after_success:
  - pip install coveralls scrutinizer-ocular
  - coveralls
  - ocular

notifications:
  email:
    on_success: never
    on_failure: change
