site_name: mine
site_description: Share application state across computers using Dropbox.
site_author: Jace Browning
repo_url: https://github.com/jacebrowning/mine

theme: readthedocs

pages:
- Home: index.md
- About:
  - Release Notes: about/changelog.md
  - Contributing: about/contributing.md
  - License: about/license.md
