site_name: mine
site_description: Share application state across computers using Dropbox.
site_author: Jace Browning

repo_url: https://github.com/jacebrowning/mine
edit_uri: https://github.com/jacebrowning/mine/edit/jacebrowning/main/docs

theme: readthedocs

nav:
  - Overview: index.md
  - About:
    - Release Notes: about/changelog.md
    - Contributor Guide: about/contributing.md
    - License: about/license.md
