site_name: mine
site_description: Share application state across computers using Dropbox.
site_author: Jace Browning
repo_url: https://github.com/jacebrowning/mine
# google_analytics: ['XX-XXXXXXXX-XX', 'auto']

theme: mkdocs

pages:
- Home: index.md
- About:
  - 'Release Notes': about/changes.md
  - Contributing: about/contributing.md
  - License: about/license.md
